language: objective-c
osx_image: xcode9.4
sudo: false
env:
  global:
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
before_install:
  - pod install
script: 
  - set -o pipefail
  - xcodebuild -workspace IGRFilterCombine.xcworkspace -scheme IGRFilterCombine -sdk iphonesimulator
